# 0 trace, 1 debug, 2 info, 3 warn, 4 error, 5 critical, 6 off
log-level: 0 # see spdlog for more log level

mount-point: "/home/ysy/nextfs/mount"

hot-spot-cache: 64

# 32K, file block, also rdma data block size
# block_size: 32768
block_size: 4096
# 4096 * 32K = 128M
block_pool_size: 4096

ipc_numa_bind: 0
ipc_pool_size: 512
ipc_channel_size: 512
rpc_numa_bind: 1
rpc_recv_head_size: 220
# 220 + 4096
rpc_mempool_blk_size: 4352
rpc_mempool_capacity: 4096
rpc_shard_num: 2
file_store_policy: "local"
dir_store_policy: "hash"

group-id: 0
server-id: 3
server-ip: 192.168.201.13
server-port: 4030

# todo
# rdma-port-id: 

in-group-node:
  - { server-id: 1, ip: 192.168.201.13, port: 4010 }  
  - { server-id: 2, ip: 192.168.201.13, port: 4020 }
  - { server-id: 3, ip: 192.168.201.13, port: 4030 }  
  - { server-id: 4, ip: 192.168.201.13, port: 4040 }

# out-group-peer-node:
#   - {group-id: 0, server-id: 1, ip: 192.168.201.13, port: 4010}
#   - {group-id: 0, server-id: 2, ip: 192.168.201.13, port: 4020}
  
root_group_id: 0
root_server_id: 1
hot-spot-cache-server-id: 2

dentry_path: "/home/ysy/data/node3/dentry_path"
metadata_path: "/home/ysy/data/node3/metadata_path"
btable_path: "//home/ysy/data/node3/btable_path"
overflow_atable_path: "/home/ysy/data/node3/overflow_atable_path"
file_inode_path: "/home/ysy/data/node3/file_inode.txt"
dir_inode_path: "/home/ysy/data/node3/dir_inode.txt"
data_block_dir: "/home/ysy/data/node3"

ipc_pool_filename: "ipc_pool_filename_11"
ipc_chnl_filename: "ipc_chnl_filename_11"
ipc_futex_filename: "ipc_futex_shm_file_11"
block_pool_filename: "data_block_file_11"








